# Generated by Django 3.2.9 on 2022-04-10 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=81)),
            ],
        ),
    ]
