# Generated by Django 3.2.9 on 2022-04-17 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0002_auto_20220410_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hints_board', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=81)),
                ('solved_board', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=81)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Easy', max_length=50)),
            ],
        ),
    ]
