# Generated by Django 3.2.9 on 2022-04-17 11:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hints_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=9), size=9),
        ),
        migrations.AlterField(
            model_name='game',
            name='solved_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=9), size=9),
        ),
    ]
