# Generated by Django 3.2.9 on 2022-06-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0005_currentdifficultylevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuokuGame',
        ),
    ]
