# Generated by Django 3.2.9 on 2022-06-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0006_delete_suokugame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentDifficultyLevel',
        ),
    ]
